name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.    
    - name: Angular Github Actions
      uses: mayur-rawte/github-angular-actions@latest
    - name: npm install
      run: npm install
    - name: ng t
      run: ng t
